const c=document.querySelector('#game'),x=c.getContext('2d'),$=s=>document.querySelector(s);
const ui={start:$('#start'),end:$('#end'),hud:$('#hud'),controls:$('#controls'),msg:$('#message'),mission:$('#mission'),fill:$('#fill'),hearts:$('#hearts'),joy:$('#joystick'),stick:$('#stick'),power:$('#rootPower'),cool:$('#cooldown')};
let W,H,D=1,last=0,playing=false,world,player,cam,joy={x:0,y:0,id:null},keys={},power=0,cool=0,healed=0,won=false,shake=0;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
function build(){world={w:2400,h:1500,grass:[],trees:[],pools:[],hearts:[],animals:[],enemies:[],dust:[],mother:{x:2150,y:750,r:72}};
 for(let i=0;i<460;i++)world.grass.push({x:rand(20,2380),y:rand(20,1480),r:rand(13,35),life:0,flower:Math.random()<.12});
 for(let i=0;i<80;i++)world.trees.push({x:rand(70,2330),y:rand(70,1430),s:rand(.75,1.3),life:0});
 for(let i=0;i<9;i++)world.pools.push({x:rand(350,2050),y:rand(180,1320),r:rand(48,75)});
 [[520,310],[1160,1190],[1770,390]].forEach((p,i)=>world.hearts.push({x:p[0],y:p[1],got:false,a:i}));
 [[800,760,'🐇'],[1450,290,'🦊'],[1750,1120,'🦌'],[1980,650,'🦋']].forEach(p=>world.animals.push({x:p[0],y:p[1],icon:p[2],free:false}));
 for(let i=0;i<12;i++)world.enemies.push({x:rand(500,2050),y:rand(150,1350),vx:rand(-.5,.5),vy:rand(-.5,.5),r:20,hp:2,hit:0});
 for(let i=0;i<85;i++)world.dust.push({x:rand(0,2400),y:rand(0,1500),s:rand(1,3)});
 player={x:180,y:750,vx:0,vy:0,r:16,hp:3,inv:0,hearts:0,animals:0,trail:[]};cam={x:0,y:0};power=0;cool=0;healed=0;won=false;updateUI()}
function begin(){build();playing=true;ui.start.classList.add('hidden');ui.end.classList.add('hidden');ui.hud.classList.remove('hidden');ui.controls.classList.remove('hidden');say('ENCUENTRA LOS 3 CORAZONES',1800)}
$('#play').onclick=begin;$('#again').onclick=begin;
function say(t,ms=1200){ui.msg.textContent=t;ui.msg.classList.remove('hidden');clearTimeout(say.t);say.t=setTimeout(()=>ui.msg.classList.add('hidden'),ms)}
function updateUI(){if(!player)return;ui.mission.textContent=`CORAZONES ${player.hearts}/3 · ANIMALES ${player.animals}/4`;ui.fill.style.width=`${Math.min(100,healed)}%`;ui.hearts.textContent='♥'.repeat(player.hp)+'♡'.repeat(3-player.hp);ui.cool.style.height=`${cool*100}%`}
function joyMove(e){let r=ui.joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy)||1,m=30;if(d>m){dx*=m/d;dy*=m/d}joy.x=dx/m;joy.y=dy/m;ui.stick.style.transform=`translate(${dx}px,${dy}px)`}
ui.joy.onpointerdown=e=>{joy.id=e.pointerId;ui.joy.setPointerCapture(e.pointerId);joyMove(e)};ui.joy.onpointermove=e=>{if(e.pointerId===joy.id)joyMove(e)};ui.joy.onpointerup=ui.joy.onpointercancel=()=>{joy.id=null;joy.x=joy.y=0;ui.stick.style.transform='translate(0,0)'};
function cast(){if(!playing||cool>0)return;power=.01;cool=1;ui.power.classList.add('active');setTimeout(()=>ui.power.classList.remove('active'),160)}ui.power.onpointerdown=e=>{e.preventDefault();cast()};
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key===' ')cast()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function update(dt){if(!playing)return;let dx=joy.x+(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=joy.y+(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),d=Math.hypot(dx,dy)||1;if(Math.hypot(dx,dy)>1){dx/=d;dy/=d}player.vx+=(dx*.015*dt);player.vy+=(dy*.015*dt);player.vx*=Math.pow(.974,dt);player.vy*=Math.pow(.974,dt);let sp=Math.hypot(player.vx,player.vy),max=.34;if(sp>max){player.vx*=max/sp;player.vy*=max/sp}player.x=clamp(player.x+player.vx*dt,20,world.w-20);player.y=clamp(player.y+player.vy*dt,20,world.h-20);player.inv=Math.max(0,player.inv-dt);cool=Math.max(0,cool-dt*.00032);if(power>0){power+=dt*.0017;if(power>1)power=0}
 player.trail.unshift({x:player.x,y:player.y});if(player.trail.length>16)player.trail.pop();let range=power?65+power*170:48;
 for(const g of world.grass)if(g.life<1&&dist(player,g)<range){g.life=Math.min(1,g.life+dt*(power?.003:.0012));healed+=dt*(power?.00017:.00006)}
 for(const t of world.trees)if(t.life<1&&dist(player,t)<range+20)t.life=Math.min(1,t.life+dt*.0015);
 for(const h of world.hearts)if(!h.got&&dist(player,h)<42){h.got=true;player.hearts++;cool=0;say('CORAZÓN DEL BOSQUE RECUPERADO');shake=12}
 for(const a of world.animals)if(!a.free&&dist(player,a)<range){a.free=true;player.animals++;healed+=6;say(`${a.icon} ANIMAL RESCATADO`)}
 for(const e of world.enemies){if(e.hp<=0)continue;e.hit=Math.max(0,e.hit-dt);let q=dist(player,e);if(q<260){e.vx+=(player.x-e.x)/(q||1)*.002*dt;e.vy+=(player.y-e.y)/(q||1)*.002*dt}e.vx*=.99;e.vy*=.99;e.x+=e.vx*dt;e.y+=e.vy*dt;if(power&&q<range+e.r&&e.hit<=0){e.hp--;e.hit=300;shake=5}if(q<player.r+e.r&&player.inv<=0){player.hp--;player.inv=1500;shake=15;say('¡LA CONTAMINACIÓN TE DEBILITA!');if(player.hp<=0){player.hp=3;player.x=180;player.y=750;say('EL BOSQUE TE HA HECHO RENACER',1800)}}}
 if(player.hearts===3&&dist(player,world.mother)<105&&!won){won=true;playing=false;healed=Math.max(healed,100);updateUI();setTimeout(()=>{ui.hud.classList.add('hidden');ui.controls.classList.add('hidden');ui.end.classList.remove('hidden');$('#result').innerHTML=`Has sanado el bosque, reunido sus 3 corazones<br>y rescatado ${player.animals} animales.`},700)}
 cam.x+=(clamp(player.x-W/2,0,world.w-W)-cam.x)*.08;cam.y+=(clamp(player.y-H/2,0,world.h-H)-cam.y)*.08;shake*=.88;updateUI()}
function circle(px,py,r,col,a=1){x.globalAlpha=a;x.fillStyle=col;x.beginPath();x.arc(px-cam.x,py-cam.y,r,0,7);x.fill();x.globalAlpha=1}
function draw(){let sx=rand(-shake,shake),sy=rand(-shake,shake);x.save();x.translate(sx,sy);let bg=x.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#303d37');bg.addColorStop(1,'#181d19');x.fillStyle=bg;x.fillRect(-20,-20,W+40,H+40);if(!world){x.restore();return}
 for(const g of world.grass){if(g.x<cam.x-40||g.x>cam.x+W+40||g.y<cam.y-40||g.y>cam.y+H+40)continue;circle(g.x,g.y,g.r,'#373c35');if(g.life){circle(g.x,g.y,g.r*g.life,`hsl(${90+g.x%12} 40% ${27+g.life*12}%)`);if(g.life>.8&&g.flower)circle(g.x,g.y,3,['#ffe27a','#efa4bc','#ceb1ff'][Math.floor(g.x)%3])}}
 for(const p of world.pools){circle(p.x,p.y,p.r,'#17191b');circle(p.x,p.y,p.r*.72,'#493849');circle(p.x-15,p.y-10,7,'#84667d',.6)}
 for(const t of world.trees){if(t.x<cam.x-60||t.x>cam.x+W+60||t.y<cam.y-70||t.y>cam.y+H+70)continue;x.lineCap='round';x.strokeStyle=t.life>.3?'#654b31':'#222421';x.lineWidth=8*t.s;x.beginPath();x.moveTo(t.x-cam.x,t.y-cam.y+25*t.s);x.lineTo(t.x-cam.x,t.y-cam.y-20*t.s);x.stroke();if(t.life>0){circle(t.x,t.y-33*t.s,25*t.s,'#538342',t.life);circle(t.x-17*t.s,t.y-23*t.s,18*t.s,'#699b4b',t.life)}}
 for(const h of world.hearts)if(!h.got){let yy=h.y+Math.sin(performance.now()*.003+h.a)*7;circle(h.x,yy,22,'#b7ee65',.16);circle(h.x,yy,12,'#b7ee65');x.font='15px serif';x.fillText('♥',h.x-cam.x-7,yy-cam.y+5)}
 for(const a of world.animals)if(!a.free){circle(a.x,a.y,27,'#151c18',.8);x.font='25px serif';x.fillText(a.icon,a.x-cam.x-13,a.y-cam.y+9)}
 for(const e of world.enemies)if(e.hp>0){circle(e.x,e.y,e.r+4,'#251f26');circle(e.x,e.y,e.r,e.hit?'#91627d':'#583c52');circle(e.x-6,e.y-3,3,'#dca0b7');circle(e.x+6,e.y-3,3,'#dca0b7')}
 let m=world.mother;circle(m.x,m.y,m.r+22,'#a3e665',.08);x.strokeStyle=player.hearts===3?'#956d3d':'#3e3930';x.lineWidth=22;x.beginPath();x.moveTo(m.x-cam.x,m.y-cam.y+55);x.lineTo(m.x-cam.x,m.y-cam.y-42);x.stroke();circle(m.x,m.y-65,m.r,player.hearts===3?'#6da24f':'#343933');x.font='900 10px Nunito';x.fillStyle='#fff';x.textAlign='center';x.fillText(player.hearts===3?'VUELVE AL ÁRBOL MADRE':'ÁRBOL MADRE',m.x-cam.x,m.y-cam.y+100);x.textAlign='start';
 for(let i=player.trail.length-1;i>0;i--){let q=player.trail[i];circle(q.x,q.y,4*(1-i/player.trail.length),'#92da55',.3)}if(power){x.strokeStyle=`rgba(190,243,111,${1-power})`;x.lineWidth=6;x.beginPath();x.arc(player.x-cam.x,player.y-cam.y,65+power*170,0,7);x.stroke()}circle(player.x,player.y,player.r+7,'#9ae55a',player.inv?Math.sin(performance.now()*.02)*.3+.4:.16);circle(player.x,player.y,player.r,'#77be49');circle(player.x-5,player.y-2,2,'#172019');circle(player.x+5,player.y-2,2,'#172019');x.strokeStyle='#b5ec70';x.lineWidth=4;x.beginPath();x.moveTo(player.x-cam.x,player.y-cam.y-11);x.quadraticCurveTo(player.x-cam.x-12,player.y-cam.y-27,player.x-cam.x-20,player.y-cam.y-17);x.stroke();x.restore()}
function loop(n){let dt=Math.min(32,n-last||16);last=n;update(dt);draw();requestAnimationFrame(loop)}build();requestAnimationFrame(loop);
